### ISSUE TITLE
TODO - update README

### ISSUE THREAD

**Issue by lgatto** [UCLouvain-CBIO/2023-scplainer#1]
- title and abstract
- link to preprint (when available)
- link to scp
- link to scpdata

**Comment by cvanderaa** [comment]
Done in https://github.com/UCLouvain-CBIO/2023-scplainer/commit/f4cbb2b1dabf373257f01e722c4f6ccb1fbb38de

Maybe leave the issue open to remind me to update the citation once available on biorXiv.
